# Generated by Django 2.2.3 on 2019-07-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_projects_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('completed', 'Complete'), ('ongoing', 'Ongoing')], default='completed', max_length=100),
        ),
    ]
