# Generated by Django 2.2.3 on 2019-08-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, help_text='Any outside link', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='The actual Blog Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Title the post will bear', max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='git_link',
            field=models.URLField(blank=True, help_text='GitHub link to the project', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='idea',
            field=models.CharField(blank=True, help_text='The idea behind the project', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_link',
            field=models.URLField(blank=True, help_text='The website of the project online', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('completed', 'Complete'), ('ongoing', 'Ongoing')], default='completed', help_text='Status of the project', max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(help_text='Title of the project', max_length=100),
        ),
    ]
