# Generated by Django 2.2.3 on 2019-08-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190801_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='technologies',
            field=models.CharField(blank=True, help_text='The technologies which have made the project', max_length=100, null=True),
        ),
    ]
